server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    preferIpAddress: true
    hostName: 192.168.43.77

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: adolescent-service
          uri: lb://ADOLESCENT-SERVICE
          predicates:
            - Path=/adolescente/**
        - id: address-service
          uri: lb://address-SERVICE
          predicates:
            - Path=/**