server:
    port: 8093

spring:
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/db_adolescent
        username: postgres
        password: admin
        pool:
            enabled: true
            initial-size: 1
            max-size: 1
    application:
        name: adolescent-service


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8099/eureka/
    instance:
        preferIpAddress: true
        hostName: 192.168.43.77